-- INSERT_USER_APPLICATION
INSERT INTO USER_MODULE (USERID, NAME, DISTRICT, AADHAARNUMBER, INCOME, APPLICATIONSTATUS, PROGRESSSTAGE, SUBMITTEDON)
VALUES (%s, %s, %s, %s, %s, 'Pending', 'Not Started', CURRENT_TIMESTAMP());

-- FETCH_USERID_QUERY
SELECT USERID, NAME, DISTRICT, AADHAARNUMBER, INCOME
FROM USER_MODULE
WHERE NAME = %s AND AADHAARNUMBER = %s;

-- UPDATE_USER_PROJECT_PROGRESS
UPDATE USER_MODULE
SET PROGRESSSTAGE = %s,
    LASTUPDATED = CURRENT_TIMESTAMP()
WHERE USERID = %s;

-- FETCH_PENDING_APPLICATIONS
SELECT USERID, NAME, DISTRICT, AADHAARNUMBER, INCOME, APPLICATIONSTATUS
FROM USER_MODULE
WHERE APPLICATIONSTATUS = 'Pending';

-- UPDATE_USER_STATUS
UPDATE USER_MODULE
SET APPLICATIONSTATUS = 'Accepted'
WHERE USERID = %s AND INITCAP(DISTRICT) = %s;

-- UPDATE_PMAY_DATA
UPDATE PMAY_DATA
SET BENEFICIARY_SELECTION = BENEFICIARY_SELECTION + 1,
    UNSTARTED = UNSTARTED + 1
WHERE DISTRICT = %s;

-- UPDATE_USER_OFFICER_ID
UPDATE USER_MODULE
SET OFFICER_ID = %s
WHERE USERID = %s;


-- FETCH_PROGRESS_NOT_STARTED
SELECT USERID, NAME, DISTRICT, OFFICER_ID, PROGRESSSTAGE
FROM USER_MODULE
WHERE PROGRESSSTAGE != 'Not Started';

-- UPDATE_PMARY_PROGRESS_FOUNDATION
UPDATE PMAY_DATA
SET FOUNDATION = FOUNDATION + 1, 
    UNSTARTED = UNSTARTED - 1
WHERE DISTRICT = %s;

-- UPDATE_PMARY_PROGRESS_LINTEL
UPDATE PMAY_DATA
SET LINTEL = LINTEL + 1, 
    FOUNDATION = FOUNDATION - 1
WHERE DISTRICT = %s;

-- UPDATE_PMARY_PROGRESS_ROOF
UPDATE PMAY_DATA
SET ROOF = ROOF + 1, 
    LINTEL = LINTEL - 1
WHERE DISTRICT = %s;

-- UPDATE_PMARY_PROGRESS_COMPLETED
UPDATE PMAY_DATA
SET COMPLETED = COMPLETED + 1, 
    ROOF = ROOF - 1
WHERE DISTRICT = %s;

-- UPDATE_USER_FOUNDATION_URL
UPDATE USER_MODULE
SET FOUNDATIONVERF = %s, 
    LASTUPDATED = CURRENT_TIMESTAMP()
WHERE USERID = %s;

-- UPDATE_USER_LINTEL_URL
UPDATE USER_MODULE
SET LINTELVERF = %s, 
    LASTUPDATED = CURRENT_TIMESTAMP()
WHERE USERID = %s;

-- UPDATE_USER_ROOF_URL
UPDATE USER_MODULE
SET ROOFVERF = %s, 
    LASTUPDATED = CURRENT_TIMESTAMP()
WHERE USERID = %s;

-- UPDATE_USER_COMPLETED_URL
UPDATE USER_MODULE
SET COMPLETEDVERF = %s, 
    LASTUPDATED = CURRENT_TIMESTAMP()
WHERE USERID = %s;

-- UPDATE_USER_SANITATION_URL
UPDATE USER_MODULE
SET SANITATIONVERF = %s, 
    LASTUPDATED = CURRENT_TIMESTAMP()
WHERE USERID = %s;


-- FETCH_USERS_WITH_COMPLETEDVERF
SELECT USERID, NAME, DISTRICT, AADHAARNUMBER, INCOME, COMPLETEDVERF
FROM USER_MODULE
WHERE COMPLETEDVERF IS NOT NULL 
  AND COMPLETEDVERF != '' 
  AND SANITATIONVERF IS NULL;


-- UPDATE_PMARY_PROGRESS_FOUNDATION
UPDATE PMAY_DATA
SET FOUNDATION = FOUNDATION + 1, 
    UNSTARTED = UNSTARTED - 1
WHERE DISTRICT = %s;

-- UPDATE_PMARY_PROGRESS_LINTEL
UPDATE PMAY_DATA
SET LINTEL = LINTEL + 1, 
    FOUNDATION = FOUNDATION - 1
WHERE DISTRICT = %s;

-- UPDATE_PMARY_PROGRESS_ROOF
UPDATE PMAY_DATA
SET ROOF = ROOF + 1, 
    LINTEL = LINTEL - 1
WHERE DISTRICT = %s;

-- UPDATE_PMARY_PROGRESS_COMPLETED
UPDATE PMAY_DATA
SET COMPLETED = COMPLETED + 1, 
    ROOF = ROOF - 1
WHERE DISTRICT = %s;



-- FETCH_TOTAL_BENEFICIARIES
SELECT 
    SUM(BENEFICIARY_SELECTION) AS total_beneficiaries
FROM PMAY_DB.HOUSING.PMAY_DATA;

-- FETCH_COMPLETED_HOMES
SELECT 
    SUM(COMPLETED) AS total_completed_houses
FROM PMAY_DB.HOUSING.PMAY_DATA;

-- FETCH_UNSTARTED_PROJECTS
SELECT 
    SUM(UNSTARTED) AS total_unstarted_projects
FROM PMAY_DB.HOUSING.PMAY_DATA;

-- FETCH_STAGE_PROGRESS
SELECT 
    SUM(FOUNDATION) AS total_foundation_progress,
    SUM(LINTEL) AS total_lintel_progress,
    SUM(ROOF) AS total_roof_progress
FROM PMAY_DB.HOUSING.PMAY_DATA;


-- FETCH_PERFORMANCE_RANKING
SELECT 
    DISTRICT, 
    (SUM(COMPLETED) / NULLIF(SUM(BENEFICIARY_SELECTION), 0)) * 100 AS completion_rate
FROM PMAY_DB.HOUSING.PMAY_DATA
GROUP BY DISTRICT
ORDER BY completion_rate DESC;




-- FETCH_DISTRICT_DATA
SELECT 
    DISTRICT, 
    FOUNDATION, 
    LINTEL, 
    ROOF, 
    COMPLETED
FROM PMAY_DB.HOUSING.PMAY_DATA
WHERE DISTRICT =  %s;



-- FETCH_DISTINCT_DISTRICTS
SELECT DISTINCT DISTRICT 
FROM PMAY_DB.HOUSING.PMAY_DATA;


-- UPDATE_COMPLAINT
UPDATE PMAY_DB.HOUSING.ADMIN_MODULE
SET COMPLAINT = %s



